services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: trade-collector-app
    command: "uv run main.py"
    env_file:
      - ../.env
    volumes:
      - ..:/app/
    depends_on:
      - timescaledb

    networks:
      - backend

networks:
  backend:
    driver: bridge
    external: true