version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    env_file:
      - ../.env

    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge